### ISSUE TITLE
Hi I just downloaded the code from git hub. But i am unable to run this app as i am getting clang error.

### ISSUE THREAD

**Issue by prabha1989** [PowaPOS/hello-powapos-t25-ios#1]

**Comment by anthonypowa** [comment]
Please go to the powapos developers portal at http://powaposdeveloper.powa.com/

For the latest version of the PowaPOS SDK.

**Comment by prabha1989** [comment]
Thanks Powa the latest sdk from the developer portal is working. Thank you once again for the quick response.
